### PR TITLE
Fix: Run CI on Postgres.

### PR DESCRIPTION
**Pull request by bjones1**
Aack! I thought we were already running CI using Postgres....but that wasn't true. It is now.

### CODE REVIEW

**Comment by bnmnetp** [comment]
This seems to duplicate all of your logging work in a previous PR??

**Comment by bjones1** [comment]
Yes, I left it a draft for this reason -- fixes here needed fixes from #66 as well. I'd suggest merging that first, then I'll update this.

**Comment by bjones1** [comment]
**Important note**: I had to [remove the index from the courses table](https://github.com/bnmnetp/BookServer/pull/67/files#diff-5fc395447ecbf46aa65df0cc2881c0e603a221f0f7c494216654af3ddefd6822L348) to avoid weird Postgres error. I suggest we merge this first then investigate what's going on. Other than that, the changes are mainly to the test setup.

**Comment by bjones1** [comment]
@bnmnetp, this is ready for your review.

**Comment by bnmnetp** [comment]
Interesting, I'll bet that postgres creates an index to enforce the uniqueness constraint.

**Review by bnmnetp — APPROVED** [review]

**Pull request merged**
